# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WepB8rY5KtnTV64d3Lb2oGpzeamMWjGn
"""

def getget_key():
  """Prompts the user for an eight-character encryption key."""
  while True:
    key = input("Enter an eight-character encryption key: ")
    if len(key) == 8:
      return key
    else:
      print("Invalid key length. Please enter eight characters.")

def encrypt(key, message):
  """Encrypts a message using a Caesar cipher with the given key.

  Args:
      key: A string containing the eight-character encryption key.
      message: The message to encrypt.

  Returns:
      The encrypted message.
  """
  encrypted_message = ""
  for char in message:
    shift = ord(key[ord(char) % 8]) - ord('a')
    new_char = chr((ord(char) + shift) % 26 + ord('a'))
    encrypted_message += new_char
  return encrypted_message

def decrypt(key, encrypted_message):
  """Decrypts an encrypted message using a Caesar cipher with the given key.

  Args:
      key: A string containing the eight-character encryption key.
      message: The encrypted message to decrypt.

  Returns:
      The decrypted message.
  """
  decrypted_message = ""
  for char in encrypted_message:
    shift = ord(key[ord(char) % 8]) - ord('a')
    new_char = chr((ord(char) - shift) % 26 + ord('a'))
    decrypted_message += new_char
  return decrypted_message

def save_message(filename, message):
  """Saves a message to a file.

  Args:
      filename: The name of the file to save the message to.
      message: The message to save.
  """
  with open(filename, "w") as f:
    f.write(message)

def main():
  """Prompts the user for a message, encrypts it, saves it to a file, and then decrypts it."""
  key = get_key()
  message = input("Enter a message to encrypt: ")
  encrypted_message = encrypt(key, message)

  save_filename = input("Enter a filename to save the encrypted message: ")
  save_message(save_filename, encrypted_message)

  decrypted_message = decrypt(key, encrypted_message)
  print("Decrypted message:", decrypted_message)

if __name__ == "__main__":
  main()